### PR TITLE
pyon: encode subclasses of base types

### PR DESCRIPTION
**Pull request by drewrisinger**
# ARTIQ Pull Request

## Description of Changes

Allow PYON to encode simple Python objects like NamedTuples and lists.
**Rationale**: have more readable and understandable data structures on client side for sending data to the target. For example, we are sending graph edges across PYON, encoded something like `start_position, destination_position, edge_type`. When these are all just numbers, it's a lot easier to understand them if we know the data structure like in a NamedTuple. A class would be ideal, but apparently too complex to be used by PYON.

### Related Issue

#1218 

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :sparkles: New feature |

### All Pull Requests

- [x] Use correct spelling and grammar.
- [x] Update [RELEASE_NOTES.md](../RELEASE_NOTES.md) if there are noteworthy changes, especially if there are changes to existing APIs.
- [x] Close/update issues.
- [x] Check the copyright situation of your changes and sign off your patches (`git commit --signoff`, see [copyright](../CONTRIBUTING.rst#copyright-and-sign-off)).

### Code Changes

- [x] Run `flake8` to check code style (follow PEP-8 style). `flake8` has issues with parsing Migen/gateware code, ignore as necessary.
- [x] Test your changes or have someone test them. Mention what was tested and how. **Ran test_serialization.py, and added new tests.**
- [x] Add and check docstrings and comments
- [x] Check, test, and update the [unittests in /artiq/test/](../artiq/test/) or [gateware simulations in /artiq/gateware/test](../artiq/gateware/test)

### Documentation Changes

- [x] Check, test, and update the documentation in [doc/](../doc/). Build documentation (`cd doc/manual/; make html`) to ensure no errors.

### Git Logistics

- [x] Split your contribution into logically separate changes (`git rebase --interactive`). Merge/squash/fixup commits that just fix or amend previous commits. Remove unintended changes & cleanup. See [tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase).
- [x] Write short & meaningful commit messages. Review each commit for messages (`git show`). Format:
  ```
  topic: description. < 50 characters total.
  
  Longer description. < 70 characters per line
  ```

### Licensing

See [copyright & licensing for more info](https://github.com/m-labs/artiq/blob/master/CONTRIBUTING.rst#copyright-and-sign-off).
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and are licensed under LGPLv3+.

### CODE REVIEW

**Comment by dnadlinger** [comment]
Hmm… While I agree that support for richer types would be useful and natural in our Python-only ecosystem, it currently has the nice property that encoding is bijective – you always get back the objects you put in. I had similarly extended PYON a while ago with support for enum values, but decided to revert (i.e. not to upstream) that after all, as the type difference made user code more brittle than I thought.

**Comment by jordens** [comment]
I'd also prefer this to be round-trip preserving.
And the other area where things need to be serialized is HDF5. We should keep the overlap maximal.

**Comment by sbourdeauducq** [comment]
@dnadlinger @jordens Agreed.

**Comment by drewrisinger** [comment]
So would this be accepted if we came up with a way to generate the same data on the other end? Something like `pickle` [protocol 0/1](https://docs.python.org/3/library/pickle.html#data-stream-format), perhaps? Or just adding specific types in for namedtuple/other basic collections?

**Comment by drewrisinger** [comment]
Also relevant, there are no mentions in the ARTIQ documentation about what types are PYON-serializable. This leads to trial-and-error or needing to read the source code.

Further, there are no negative tests in `test_serialization.py`, i.e. no tests that if you feed in an incorrect datatype that PYON will throw an error or anything. Leads to congruence bias.

**Comment by drewrisinger** [comment]
@sbourdeauducq @jordens @dnadlinger 
(not sure if you still get notifications from closed threads)

**Comment by sbourdeauducq** [comment]
I don't see how it can be possible to come up with a way to transfer arbitrary Python objects that doesn't introduce other issues, such as being compatible only with the exact same ARTIQ/Python/other packages being installed and running at both communicating ends.

As for documentation etc. the problem is funding and manpower as usual - would you be able to help?

**Pull request closed without merging**
