### PR TITLE
Docvivado

### PR DESCRIPTION
**Pull request by jbqubit**
# ARTIQ Pull Request

### Related Issue

https://github.com/m-labs/artiq/issues/1714

Changes:
- reference Vivado version in nix script
- remove attempt to track time-varying Vivado installation problems and instead refer users to the Forum 

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :scroll: Docs |

### Documentation Changes

- [x] Check, test, and update the documentation in [doc/](../doc/). Build documentation (`cd doc/manual/; make html`) to ensure no errors.

### CODE REVIEW

**Comment by jbqubit** [comment]
OK well this pull request is a mess. Just look at this commit for the proposed documentation edit. 

https://github.com/m-labs/artiq/pull/1715/commits/13367ed2bc40db9452454c2a86562b3b6f18835b

**Comment by sbourdeauducq** [comment]
This removes important information.

**Comment by jbqubit** [comment]
The main change that I'd like to see is for the documentation to include a link to the nix-script for vivado. This is part of the breadcrumb trail that helps users bootstrap their development chops. This file location has been static for over two years. And from what I can tell there's not a big refactoring of nix-scripts in the pipeline.

https://git.m-labs.hk/M-Labs/nix-scripts/src/branch/master/artiq-fast/vivado.nix

**Comment by sbourdeauducq** [comment]
> from what I can tell there's not a big refactoring of nix-scripts in the pipeline.

With the plans to switch to RISC-V, upstream/newer LLVM, NAC3 and the eventual merging of the artiq-zynq repos into the main one, there definitely will be major changes to nix-scripts.

**Comment by jbqubit** [comment]
Thank you. Your edit is sufficient. :)

**Pull request closed without merging**
