### PR TITLE
fixed value scaling issue for the center scan gui widget

### PR DESCRIPTION
**Pull request by lriesebos**
# ARTIQ Pull Request

## Description of Changes

Fixed a bug in the center scan widget that causes scaling to be applied twice.
Fix applies both to master and release-5 branch, I would like to have the patch on the release-5 branch.

### Related Issue

No related issues.

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |

### All Pull Requests

- [x] Use correct spelling and grammar.
- [x] Update [RELEASE_NOTES.md](../RELEASE_NOTES.md) if there are noteworthy changes, especially if there are changes to existing APIs.
- [x] Close/update issues.
- [x] Check the copyright situation of your changes and sign off your patches (`git commit --signoff`, see [copyright](../CONTRIBUTING.rst#copyright-and-sign-off)).

### Code Changes

Changes too small to affect the points below.

- [x] Run `flake8` to check code style (follow PEP-8 style). `flake8` has issues with parsing Migen/gateware code, ignore as necessary.
- [x] Test your changes or have someone test them. Mention what was tested and how.
- [x] Add and check docstrings and comments
- [x] Check, test, and update the [unittests in /artiq/test/](../artiq/test/) or [gateware simulations in /artiq/gateware/test](../artiq/gateware/test)

### Documentation Changes

Changes too small to affect the points below.

- [x] Check, test, and update the documentation in [doc/](../doc/). Build documentation (`cd doc/manual/; make html`) to ensure no errors.

### Git Logistics

- [x] Split your contribution into logically separate changes (`git rebase --interactive`). Merge/squash/fixup commits that just fix or amend previous commits. Remove unintended changes & cleanup. See [tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase).
- [x] Write short & meaningful commit messages. Review each commit for messages (`git show`). Format:
  ```
  topic: description. < 50 characters total.
  
  Longer description. < 70 characters per line
  ```

### Licensing

See [copyright & licensing for more info](https://github.com/m-labs/artiq/blob/master/CONTRIBUTING.rst#copyright-and-sign-off).
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and are licensed under LGPLv3+.

### CODE REVIEW

**Comment by lriesebos** [comment]
Just to add, a minimal example to reproduce the addressed bug using the ARTIQ dashboard.

```python
from artiq.experiment import *


class CenterScanBugExperiment(EnvExperiment):

    def build(self):
        # See https://github.com/m-labs/artiq/pull/1538
        self.scan = self.get_argument('scan',
                                      Scannable(default=CenterScan(42862.0 * kHz, 76 * kHz, 2 * kHz),
                                                ndecimals=3,
                                                unit='kHz'))

    def run(self):
        print(self.scan.describe())
```

**Comment by lriesebos** [comment]
@jordens , when do you think you have time to take a look at this pull request? It consists of only 3 line changes and will (supposedly) fix a bug with center scan that we see daily in our lab.

**Comment by jordens** [comment]
The change looks valid. I haven't tested it.

**Comment by jordens** [comment]
@lriesebos Does this also apply to master?

**Comment by jordens** [comment]
You say it does. I assume that means you identified the bug there as well.

**Comment by lriesebos** [comment]
@jordens yes, last time I checked it was the same for master. tnx for the quick reply!

**Pull request merged**
