### PR TITLE
Remove hack: Not required anymore

### PR DESCRIPTION
**Pull request by Deepskyhunter**
# ARTIQ Pull Request

## Type of Changes

|   | Type |
| ------------- | ------------- |
|   | :bug: Bug fix  |
|   | :sparkles: New feature |
|   | :hammer: Refactoring  |
|   | :scroll: Docs |

### All Pull Requests

- [x] Use correct spelling and grammar.

### Code Changes

- [x] Test your changes or have someone test them. Mention what was tested and how.

### Git Logistics

- [x] Split your contribution into logically separate changes (`git rebase --interactive`). Merge/squash/fixup commits that just fix or amend previous commits. Remove unintended changes & cleanup. See [tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase).
- [x] Write short & meaningful commit messages. Review each commit for messages (`git show`). Format:
  ```
  topic: description. < 50 characters total.
  
  Longer description. < 70 characters per line
  ```

### Licensing

See [copyright & licensing for more info](https://github.com/m-labs/artiq/blob/master/CONTRIBUTING.rst#copyright-and-sign-off).
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and are licensed under LGPLv3+.

### CODE REVIEW

**Comment by sbourdeauducq** [comment]
How did you test?
Please improve the commit message.

**Comment by Deepskyhunter** [comment]
I first filled the buffer with 1000 messages, then submit another test.
The new log message should be added and the scroll should be at the bottom all the time.
Should these information included in commit message?

**Comment by sbourdeauducq** [comment]
> I first filled the buffer with 1000 messages, then submit another test.

How many times? With what scrollbar positions?

The comment said the issue is intermittent.

**Comment by Deepskyhunter** [comment]
> The comment said the issue is intermittent.

I tested 5 times before you remind me that each time with the scroll position at the bottom and at the middle. But now when I try again. The bug still exist.

**Pull request closed without merging**
