### PR TITLE
Add floating-point instruction support to kernel for non-Kasli-v1.x targets

### LINKED ISSUE #535: gateware floating point instructions on the kernel CPU
https://github.com/m-labs/artiq/issues/529#issuecomment-237135917

### PR DESCRIPTION
**Pull request by occheung**
# ARTIQ Pull Request

### CPU
All targets except Kasli v1.x:
- Enabled an FPU from VexRiscv in kernel_cpu (see VexRiscv_G variant of VexRiscv in MiSoC)
- Select 64-bits data-path / comm CPU data width, to accommodate the FPU.
- Implement 64-bits support to submodules (DMA, DRTIO).

FPU is not supported in Kasli, due to timing issue.

### Test
Performance is tested by running `mandelbrot.py` on kc705 nist_clock variant.
Before this patch: 6.03563 seconds
After this patch: 3.88476 seconds

DRTIO is tested using a Kasli v1.1 master and a Kasli v2.0 satellite.

### ~~TODO~~
~~Bump llvmlite to include [a patch for hard-float ABI in RISC-V](https://github.com/numba/llvmlite/pull/775).~~

### Related Issue
Closes #535

### Potentially breaking
- Endianness: Sayma_AMC (Previously fixed in #1769)
- ~~Adding a check on the ABI when loading library for kernel may cause `test_rtio_counter` to fail on Kasli v1.1.~~

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :sparkles: New feature |

### All Pull Requests

- [x] Use correct spelling and grammar.
- [ ] Update [RELEASE_NOTES.rst](../RELEASE_NOTES.rst) if there are noteworthy changes, especially if there are changes to existing APIs.
- [x] Close/update issues.
- [ ] Check the copyright situation of your changes and sign off your patches (`git commit --signoff`, see [copyright](../CONTRIBUTING.rst#copyright-and-sign-off)).

### Code Changes

- [x] Test your changes or have someone test them. Mention what was tested and how.
- [x] Check, test, and update the [unittests in /artiq/test/](../artiq/test/) or [gateware simulations in /artiq/gateware/test](../artiq/gateware/test)

### Git Logistics

- [x] Split your contribution into logically separate changes (`git rebase --interactive`). Merge/squash/fixup commits that just fix or amend previous commits. Remove unintended changes & cleanup. See [tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase).
- [x] Write short & meaningful commit messages. Review each commit for messages (`git show`). Format:
  ```
  topic: description. < 50 characters total.
  
  Longer description. < 70 characters per line
  ```

### Licensing

See [copyright & licensing for more info](https://github.com/m-labs/artiq/blob/master/CONTRIBUTING.rst#copyright-and-sign-off).
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and are licensed under LGPLv3+.

### CODE REVIEW

**Comment by sbourdeauducq** [comment]
> Performance is tested by running `mandelbrot.py` on kc705 nist_clock variant.
> Before this patch: 6.03563 seconds
> After this patch: 3.88476 seconds

Can you try something more representative e.g. multiply floating-point matrices? Mandelbrot also does a lot of RPC.

**Comment by sbourdeauducq** [comment]
> Adding a check on the ABI when loading library for kernel may cause `test_rtio_counter` to fail on Kasli v1.1.

Why? Shouldn't be Kasli v1 detected and the non-FPU API selected?

**Comment by occheung** [comment]
> Can you try something more representative e.g. multiply floating-point matrices? Mandelbrot also does a lot of RPC.

Modified a numpy test.
```
import sys
import numpy
from artiq.experiment import *

class FloatMatrixMul(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.a = numpy.array([[1, 2, 3], [4, 5, 6]], dtype=numpy.float64)
        self.b = numpy.array([[7, 8], [9, 10], [11, 12]], dtype=numpy.float64)

    @kernel
    def run(self):
        start_mu = self.core.get_rtio_counter_mu()
        result = self.a @ self.b
        end_mu = self.core.get_rtio_counter_mu()
        print(self.core.mu_to_seconds(end_mu - start_mu))
        print(result)
```
On kc705, the printed result shows that it took around 249us without FPU, and 4.90us with FPU.

**Comment by sbourdeauducq** [comment]
Try running that multiplication 10000 times with a for loop (perhaps on the previous result to avoid compiler optimizations).

**Comment by occheung** [comment]
> Why? Shouldn't Kasli v1 be detected and the non-FPU API selected?

Yes. This is only to avoid linking invalid libraries by accident (i.e. non-float ABI to double-float ABI). It is to serve similar purpose as the other checks in dyld, such as the ELF magic, ELF architecture code etc.

It can be removed.

**Comment by sbourdeauducq** [comment]
Keeping it sounds good, but I don't see why it would ever cause a problems with tests.

**Comment by occheung** [comment]
```
import sys
import numpy
from artiq.experiment import *

class FloatMatrixMul(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.a = numpy.array([[1, 2, 3], [4, 5, 6]], dtype=numpy.float64)
        self.b = numpy.array([[7, 8], [9, 10], [11, 12]], dtype=numpy.float64)
        self.square = numpy.array([[1.005, -0.001], [0.007, 0.993]], dtype=numpy.float64)

    @kernel
    def run(self):
        start_mu = self.core.get_rtio_counter_mu()
        result = self.a @ self.b
        for i in range(10000):
            result = result @ self.square
        end_mu = self.core.get_rtio_counter_mu()
        print(self.core.mu_to_seconds(end_mu - start_mu))
        print(result)
```
Added `self.square`.
1.36 seconds without FPU, 0.0242 seconds with FPU.

**Comment by sbourdeauducq** [comment]
Add the llvmlite patches to flake.nix
https://git.m-labs.hk/M-Labs/nix-scripts/raw/branch/master/artiq-fast/pkgs/llvmlite-llvm11.nix
https://git.m-labs.hk/M-Labs/nix-scripts/raw/branch/master/artiq-fast/pkgs/llvmlite-callsite.diff

**Comment by occheung** [comment]
> Keeping it sounds good, but I don't see why it would ever cause a problems with tests.

Apparently `test_rtio_counter` test already fails occasionally before this. My mistake.

**Comment by fanmingyu212** [comment]
@occheung it is exciting to see these floating point performance improvements! would you comment more on the implications of this PR for different systems? From my understanding, Kasli v1.x receives no updates (and there is no plan to update it soon), and Kasli v2.0 receives a data width update from 32 to 64, but since the FPU is not implemented, a performance gain is not expected either. Is the Kasli-SoC (and maybe other systems I don't know) the only system(s) receiving the floating point performance gain?

**Comment by occheung** [comment]
>Kasli v2.0 receives a data width update from 32 to 64, but since the FPU is not implemented, a performance gain is not expected either.

@fanmingyu212 Kasli v2 should get an FPU on the kernel after this patch. Although the performance tests above involve a kc705, the speedup should still mostly apply to kasli v2.

>Is the Kasli-SoC (and maybe other systems I don't know) the only system(s) receiving the floating point performance gain?

All other targets that uses VexRiscv cores get an FPU on the kernel (also the 64 bits data width), i.e. kasli v2, kc705 & metlino. Kasli-SOC uses Zynq core, which already has FPU support there. It should not be affected by this update.

I can probably edit the title/summary to highlight this point.

**Comment by fanmingyu212** [comment]
@occheung thank you for the reply. I initially thought Kasli 2 did not get a FPU as the summary says:

> FPU is not supported in Kasli, due to timing issue.

If you can edit this sentence it might be clearer for people not familiar with the code.

**Pull request merged**
