### PR TITLE
Urukul/SU-Servo: Use constants for default profiles

### LINKED ISSUE #1817: SU-Servo: Gateware feed ASF to outdated default profile
# Bug Report

## One-Line Summary

The SU-Servo gateware sends data to profile 0, while profile 7 is enabled by default on the CPLD.

## Issue Details

It is caused by not updating the gateware of SU-Servo after [this change of `urukul.py`](https://github.com/m-labs/artiq/pull/1584/files#diff-a0dfb7480873c5d4b9e10fb74c959614b45a36aba846c46b0fae0a4b6a713758L191) in #1584. @pmldrmota 

### Steps to Reproduce

Enable SU-Servo. Run an experiment that involves SU-Servo.

<details>
<summary>Example: (Similar to the one on artiq_sinara_tester)</summary>

```python
class SUServoExample(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.suservo = self.get_device("suservo0")
        self.suschannels = [
            self.get_device("suservo0_ch"+str(i)) for i in range(8)
        ]

    @kernel
    def run(self):
        self.core.reset()
        self.core.break_realtime()
        self.suservo.init()
        self.suservo.set_pgia_mu(0, 0)  # unity gain
        self.suservo.cplds[0].set_att(0, 15.)
        self.suschannels[0].set_y(profile=0, y=0.) # Clear integrator
        self.suschannels[0].set_iir(
            profile=0,
            adc=0,          # take data from Sampler channel 0
            kp=-1.,         # -1 P gain
            ki=0./s,        # no integrator gain
            g=0.,           # no integrator gain limit
            delay=0.        # no IIR update delay after enabling
        )
        self.suschannels[0].set_dds(
            profile=0,
            offset=-.3,     # 3 V with above PGIA settings
            frequency=10*MHz,
            phase=0.)
        # enable RF, IIR updates and set profile
        self.suschannels[0].set(en_out=1, en_iir=1, profile=0)
        self.suservo.set_config(enable=1)
```
</details>

### Expected Behavior

Urukul is able to output waveform.

### Actual (undesired) Behavior

No waveform from Urukul.

### Your System (omit irrelevant parts)

* ARTIQ version (including gateware & firmware): Latest master as of writing this issue.
* Hardware involved: SU-Servo

## Proposed Solution
Update the profile that the SU-Servo gateware will feed ASF to. ([See this line](https://github.com/m-labs/artiq/blob/master/artiq/gateware/suservo/dds_ser.py#L29))

### PR DESCRIPTION
**Pull request by occheung**
# ARTIQ Pull Request

## Description of Changes

This PR patches the issues originated from the change of default profiles in #1584.
- AD9910 & Urukul drivers now uses the default single tone profile `DEFAULT_PROFILE` (7) as the default value of both `set`/set_mu` & `get`/`get_mu` (#1809).
- RAM profile setter uses `DEFAULT_PROFILE_RAM` (0) as default.
- SU-Servo gateware now sends to the default single tone profile.

`DEFAULT_PROFILE` concerns the default value of CPLD shift register and AD9910 itself, so it is in `urukul.py`.
`_DEFAULT_PROFILE_RAM` is only referenced in AD9910, and only AD9910 has RAM mode, so it is in `ad9910.py`.
I need some feedback about the constants.

## Tests
Ran the code in the example of #1817 and getting RF signal from Urukul, controllable by Sampler.

### Related Issue
#1809 (RAM FTW/ASF/POW getter is not ported to `get`/`get_mu`)
Closes #1817

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |
| ✓  | :hammer: Refactoring  |
| ✓  | :scroll: Docs |

### All Pull Requests

- [x] Use correct spelling and grammar.
- [x] Close/update issues.

### Code Changes

- [x] Run `flake8` to check code style (follow PEP-8 style). `flake8` has issues with parsing Migen/gateware code, ignore as necessary.
- [x] Test your changes or have someone test them. Mention what was tested and how.
- [x] Add and check docstrings and comments

### Documentation Changes

- [x] Check, test, and update the documentation in [doc/](../doc/). Build documentation (`cd doc/manual/; make html`) to ensure no errors.

### Git Logistics

- [x] Split your contribution into logically separate changes (`git rebase --interactive`). Merge/squash/fixup commits that just fix or amend previous commits. Remove unintended changes & cleanup. See [tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase).
- [x] Write short & meaningful commit messages. Review each commit for messages (`git show`). Format:
  ```
  topic: description. < 50 characters total.
  
  Longer description. < 70 characters per line
  ```

### Licensing

See [copyright & licensing for more info](https://github.com/m-labs/artiq/blob/master/CONTRIBUTING.rst#copyright-and-sign-off).
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and are licensed under LGPLv3+.

### CODE REVIEW

**Comment by sbourdeauducq** [comment]
@pmldrmota

**Comment by fanmingyu212** [comment]
@occheung should the default value of `internal_profile` argument in `set_cfr1` function also use `_DEFAULT_PROFILE_RAM` instead of `0`? https://github.com/m-labs/artiq/blob/04e3a9958a46d9e84f4a11bab66aa0cf6ab59529/artiq/coredevice/ad9910.py#L381-L392

The changes look good to me. We are running our experiment (no suservo, only ad9910s) with similar changes too.

**Comment by pmldrmota** [comment]
@fanmingyu212 No, the internal_profile argument sets how many RAM profiles the hardware should visit in burst/continuous mode, see the datasheet _Table 14. RAM Internal Profile Control Modes_.

**Comment by fanmingyu212** [comment]
@pmldrmota thank you for the explanation! I agree that `internal_profile` should stay as a constant `0`.

**Comment by occheung** [comment]
Rebased to master.

**Pull request merged**
