### PR TITLE
Simplified use of the AD9910 RAM feature

### PR DESCRIPTION
**Pull request by pmldrmota**
# ARTIQ Pull Request

## Description of Changes

When working with the AD9910 RAM with internal profile control, it was necessary to reset the single-tone profile 0 register each time after switching from RAM mode to single-tone mode, because internal profile control always starts with profile 0. 
The choice of the default single-tone profile is otherwise arbitrary. I therefore propose using the last profile (7) such that 0-6 can concurrently be used for RAM playback.
Moreover, the AD9910 `set_mu` function is hereby extended to also provide the option to write to the ASF, FTW and POW registers, which are used for all parameters not controlled by the RAM, instead of writing them to the single-tone profile registers. This enables easy access to phase-coherent DDS output even with amplitude or frequency provided by the RAM.

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |

### All Pull Requests

- [x] Use correct spelling and grammar.
- [x] Update [RELEASE_NOTES.rst](../RELEASE_NOTES.rst) if there are noteworthy changes, especially if there are changes to existing APIs.
- [x] Check the copyright situation of your changes and sign off your patches (`git commit --signoff`, see [copyright](../CONTRIBUTING.rst#copyright-and-sign-off)).

### Code Changes

- [x] Run `flake8` to check code style (follow PEP-8 style). `flake8` has issues with parsing Migen/gateware code, ignore as necessary.
- [ ] Test your changes or have someone test them. Mention what was tested and how.
- [x] Add and check docstrings and comments
- [ ] Check, test, and update the [unittests in /artiq/test/](../artiq/test/) or [gateware simulations in /artiq/gateware/test](../artiq/gateware/test)

### Documentation Changes

- [x] Check, test, and update the documentation in [doc/](../doc/). Build documentation (`cd doc/manual/; make html`) to ensure no errors.

### Git Logistics

- [x] Split your contribution into logically separate changes (`git rebase --interactive`). Merge/squash/fixup commits that just fix or amend previous commits. Remove unintended changes & cleanup. See [tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase).
- [x] Write short & meaningful commit messages. Review each commit for messages (`git show`).

### Licensing

See [copyright & licensing for more info](https://github.com/m-labs/artiq/blob/master/CONTRIBUTING.rst#copyright-and-sign-off).
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and are licensed under LGPLv3+.

### CODE REVIEW

**Comment by occheung** [comment]
Tested the default profile part with the following code.
```
class UrukulExample(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.cpld = self.get_device("urukul0_cpld")
        self.dds = self.get_device("urukul0_ch2")

    def prepare(self):
        self.f = [10*MHz, 5*MHz, 2*MHz, 1*MHz]
        self.f_ram = [0] * len(self.f)
        self.dds.frequency_to_ram(self.f, self.f_ram)

    @kernel
    def run(self):
        self.core.reset()
        self.core.break_realtime()
        self.cpld.init()
        self.dds.init()

        self.core.break_realtime()
        # Setup a single-tone channel, it should use profile 7
        self.dds.set(60*MHz, amplitude=1.0)
        # CPLD should set profile 7 by default
        self.dds.set_att(6.)
        self.dds.cfg_sw(True)

        # Configure a RAM mode after delay
        delay(5*s)
        self.dds.set_cfr1(ram_enable=0)
        self.cpld.io_update.pulse_mu(8)
        self.cpld.set_profile(0)
        # RAM should select profile 0 by default
        self.dds.set_profile_ram(start=0, end=len(self.f_ram)-1,
            step=250, mode=RAM_MODE_CONT_RAMPUP)
        self.cpld.io_update.pulse_mu(8)

        self.dds.write_ram(self.f_ram)

        self.dds.set_amplitude(1.0)
        self.dds.set_cfr1(ram_enable=1, ram_destination=RAM_DEST_FTW, osk_enable=1)
        self.cpld.io_update.pulse_mu(8)

        # Switch to single-tone (profile 7)
        delay(5*s)
        self.dds.set_cfr1(ram_enable = 0)
        self.cpld.io_update.pulse_mu(8)
        self.cpld.set_profile(7)
```
The initial single tone profile can be re-enabled by disabling RAM and changing profile (to profile 7), without rewriting the profile itself. The RAM profile can also be re-enabled with the following code.
```
        self.dds.set_cfr1(ram_enable=1, ram_destination=RAM_DEST_FTW, osk_enable=1)
        self.cpld.io_update.pulse_mu(8)
        self.cpld.set_profile(0)
```

Please let me know if this is **not** the intended use case. I haven't tested the `set_mu()` and `set()` changes.

**Comment by occheung** [comment]
Tested the `set_mu()` and `set()` changes by generating the same waveform in 2 DDS channels, one with 0.5 turns phase shift.
```
    def build(self):
        self.setattr_device("core")
        self.cpld = self.get_device("urukul0_cpld")
        self.dds0 = self.get_device("urukul0_ch2")
        self.dds1 = self.get_device("urukul0_ch3")

    def prepare(self):
        self.f = [10*MHz, 5*MHz, 2*MHz, 1*MHz]
        self.f_ram = [0] * len(self.f)
        self.dds0.frequency_to_ram(self.f, self.f_ram)

    @kernel
    def run(self):
        self.core.reset()
        self.core.break_realtime()
        self.cpld.init()
        self.dds0.init()
        self.dds1.init()
        self.dds0.set_phase_mode(PHASE_MODE_TRACKING)
        self.dds1.set_phase_mode(PHASE_MODE_TRACKING)

        self.core.break_realtime()
        # Initialize digital attenuators and switches
        self.cpld.set_att(2, 6.)
        self.cpld.set_att(3, 6.)
        self.cpld.cfg_sw(2, True)
        self.cpld.cfg_sw(3, True)

        delay(1*s)
        self.dds0.set_cfr1(ram_enable=0)
        self.dds1.set_cfr1(ram_enable=0)
        self.cpld.io_update.pulse_mu(8)
        self.cpld.set_profile(0)
        self.dds0.set_profile_ram(start=0, end=len(self.f_ram)-1,
            step=250, mode=RAM_MODE_CONT_RAMPUP)
        self.dds1.set_profile_ram(start=0, end=len(self.f_ram)-1,
            step=250, mode=RAM_MODE_CONT_RAMPUP)
        self.cpld.io_update.pulse_mu(8)

        self.dds0.write_ram(self.f_ram)
        self.dds1.write_ram(self.f_ram)

        self.dds0.set(100*MHz, amplitude=1.0, phase=0.0, profile=-1)
        self.dds1.set(100*MHz, amplitude=1.0, phase=0.5, profile=-1)
        self.dds0.set_cfr1(ram_enable=1, ram_destination=RAM_DEST_FTW, osk_enable=1)
        self.dds1.set_cfr1(ram_enable=1, ram_destination=RAM_DEST_FTW, osk_enable=1)

        self.cpld.io_update.pulse_mu(8)
```

GAS0001

The thing that really irks me is the `frequency` parameter. It is mandatory, even if we are dealing with a frequency RAM profile. So there is the `100*MHz` parameter written to the FTW register even though the DDS would not use it in this situation.

**Comment by occheung** [comment]
Passed unittests in `artiq/test` on kc705.

**Comment by pmldrmota** [comment]
Thank you @occheung for testing this!

> The thing that really irks me is the frequency parameter. It is mandatory, even if we are dealing with a frequency RAM profile. So there is the 100*MHz parameter written to the FTW register even though the DDS would not use it in this situation.

I agree, there's two points:
1. writing the FTW to the DDS in this case is a waste of time. An option would be to keep the `profile` argument as-is and add a `ram_dest` argument, which helps apply only those DDS parameters that are effective.

2. The FTW argument is mandatory. For setting a single tone profile in most applications, I don't think the FTW is more "important" than the ASF. What about adding a default for the FTW, for example `0` so that it becomes obvious that this is not a useful default in single tone mode. Existing user code would still work.

Something like this:

```diff
@@ -460,8 +460,8 @@ class AD9910:
     @kernel
-    def set_mu(self, ftw, pow_=0, asf=0x3fff, phase_mode=_PHASE_MODE_DEFAULT,
-               ref_time_mu=int64(-1), profile=7):
+    def set_mu(self, ftw=0, pow_=0, asf=0x3fff, phase_mode=_PHASE_MODE_DEFAULT,
+               ref_time_mu=int64(-1), profile=7, ram_dest=-1):
         """Set DDS parameters in machine units.

         This uses machine units (FTW, POW, ASF). The frequency tuning word

@@ -481,9 +481,11 @@ class AD9910:
             by :meth:`set_phase_mode` for this call.
         :param ref_time_mu: Fiducial time used to compute absolute or tracking
             phase updates. In machine units as obtained by `now_mu()`.
-        :param profile: Profile number to set (0-7, default: 7, -1: write DDS
-            parameters to the ASF/FTW/POW registers instead of to the
-            single tone profile register).
+        :param profile: Single tone profile number to set (0-7, default: 7).
+            Ineffective if :param:`ram_dest` is specified.
+        :param ram_dest: If RAM_DEST_(ASF|POWASF|POW|FTW), write free
+            DDS parameters to the ASF/FTW/POW registers instead of to the single
+            tone profile register (default behaviour, see :param:`profile`).
         :return: Resulting phase offset word after application of phase
             tracking offset. When using :const:`PHASE_MODE_CONTINUOUS` in
             subsequent calls, use this value as the "current" phase.

@@ -507,16 +509,20 @@ class AD9910:
                 dt = int32(now_mu()) - int32(ref_time_mu)
                 pow_ += dt*ftw*self.sysclk_per_mu >> 16

-        if profile < 0:
-            self.set_asf(asf)
-            self.set_ftw(ftw)
-            self.set_pow(pow_)
-        else:
+        if ram_dest == -1:
             # The single tone profiles are being written here.
             # If using RAM later, make sure to reinitialise the
             # single tone profile registers accordingly.
             self.write64(_AD9910_REG_PROFILE0 + profile,
                          (asf << 16) | (pow_ & 0xffff), ftw)
+        else:
+            if not ram_dest == RAM_DEST_FTW:
+                self.set_ftw(ftw)
+            if not ram_dest == RAM_DEST_POWASF:
+                if not ram_dest == RAM_DEST_ASF:
+                    self.set_asf(asf)
+                if not ram_dest == RAM_DEST_POW:
+                    self.set_pow(pow_)

```
?

**Comment by occheung** [comment]
Sounds good. 158a7be.

Repeated the `set()` and `set_mu()` test above after replacing
```python
        self.dds0.set(100*MHz, amplitude=1.0, phase=0.0, profile=-1)
        self.dds1.set(100*MHz, amplitude=1.0, phase=0.5, profile=-1)
```
with
```python
        self.dds0.set(amplitude=1.0, phase=0.0, ram_destination=RAM_DEST_FTW)
        self.dds1.set(amplitude=1.0, phase=0.5, ram_destination=RAM_DEST_FTW)
```

**Pull request merged**
