### PR TITLE
release_notes: improve notes on #1544 (dataset HDF5 options)

### LINKED ISSUE #1827: TypeError on running artiq_dashboard
# Bug Report

## One-Line Summary

The dashboard does not run on current master 3f812c4c2c1c322b28a68b3e985006631db872cd. 

### Steps to Reproduce

Run `artiq_dashboard` - the process terminates with the error:
```
>python -m artiq.frontend.artiq_dashboard -s dgm
Traceback (most recent call last):
  File "c:\scratch\artiq\artiq\gui\models.py", line 413, in data
    return convert(key, self.backing_store[key],
  File "c:\scratch\artiq\artiq\dashboard\datasets.py", line 156, in convert
    return "Y" if v["persist"] else "N"
TypeError: tuple indices must be integers or slices, not str
```

From a bisection, this problem was introduced by d8b1e59538822b3377a30ba21306073f1367f3d7

### PR DESCRIPTION
**Pull request by airwoodix**
# ARTIQ Pull Request

## Description of Changes

Make steps necessary to update from ARTIQ-6 to ARTIQ-7 after #1544 more explicit.

@cjbe @hartytp do you confirm that the snippet for migrating ``dataset_db.pyon`` actually works?

### Related Issue

Closes #1827 

## Type of Changes

|   | Type |
| ------------- | ------------- |
|   | :bug: Bug fix  |
|   | :sparkles: New feature |
|   | :hammer: Refactoring  |
| ✓  | :scroll: Docs |

### All Pull Requests

- [x] Use correct spelling and grammar.
- [x] Update [RELEASE_NOTES.rst](../RELEASE_NOTES.rst) if there are noteworthy changes, especially if there are changes to existing APIs.
- [x] Close/update issues.
- [x] Check the copyright situation of your changes and sign off your patches (`git commit --signoff`, see [copyright](../CONTRIBUTING.rst#copyright-and-sign-off)).

### Documentation Changes

- [x] Check, test, and update the documentation in [doc/](../doc/). Build documentation (`cd doc/manual/; make html`) to ensure no errors.

### Git Logistics

- [x] Split your contribution into logically separate changes (`git rebase --interactive`). Merge/squash/fixup commits that just fix or amend previous commits. Remove unintended changes & cleanup. See [tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase).
- [x] Write short & meaningful commit messages. Review each commit for messages (`git show`). Format:
  ```
  topic: description. < 50 characters total.
  
  Longer description. < 70 characters per line
  ```

### Licensing

See [copyright & licensing for more info](https://github.com/m-labs/artiq/blob/master/CONTRIBUTING.rst#copyright-and-sign-off).
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and are licensed under LGPLv3+.

### CODE REVIEW

**Comment by hartytp** [comment]
Thanks @airwoodix ! Apologies for the slow response to this.

I'm not sure what @sbourdeauducq / @jordens overall policy is for documenting this kind of thing. My preference would probably to give a bit less detail in the release notes, but link to the relevant PR / issue. i.e. we should (as you do) make it clear that this is a sufficiently big change to all code that touches datasets, such as applets, but then link to the PR for more discussion. That way any further discussion is easy to find from the release notes.

**Comment by sbourdeauducq** [comment]
For version migration matters, the release notes are a good place I think.

**Comment by jordens** [comment]
I would still propose to consider [the suggestion of automatic conversion](https://github.com/m-labs/artiq/pull/1544#issuecomment-863129649). Just make sure that the release notes state that the format change will be applied automatically and is not backwards compatible.

**Comment by airwoodix** [comment]
Since #1544 was reverted in #1838, this PR is obsolete. Closing.

**Pull request closed without merging**
