### PR TITLE
Allow attaching child dataset managers

### PR DESCRIPTION
**Pull request by lriesebos**
Signed-off-by: Leon Riesebos <leon.riesebos@duke.edu>

# ARTIQ Pull Request

## Description of Changes

Allow a child dataset manager to be attached to an existing dataset manager. This allows transparent data-separation in experiment archives.

Not sure if there is interest in this feature, but we do use this to clone or isolate dataset managers in various cases. See https://gitlab.com/duke-artiq/dax/-/blob/master/dax/util/artiq.py#L289 . Now we basically [hack our way around it](https://gitlab.com/duke-artiq/dax/-/blob/master/dax/util/artiq.py#L347).

Note that this is for data separation within a single experiment and specifically the (HDF5) archive. It is NOT similar to #1614 .

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :sparkles: New feature |

### All Pull Requests

- [x] Use correct spelling and grammar.
- [x] Update [RELEASE_NOTES.rst](../RELEASE_NOTES.rst) if there are noteworthy changes, especially if there are changes to existing APIs.
- [x] Close/update issues.
- [x] Check the copyright situation of your changes and sign off your patches (`git commit --signoff`, see [copyright](../CONTRIBUTING.rst#copyright-and-sign-off)).

### Code Changes

- [x] Run `flake8` to check code style (follow PEP-8 style). `flake8` has issues with parsing Migen/gateware code, ignore as necessary.
- [x] Test your changes or have someone test them. Mention what was tested and how.
- [x] Add and check docstrings and comments
- [x] Check, test, and update the [unittests in /artiq/test/](../artiq/test/) or [gateware simulations in /artiq/gateware/test](../artiq/gateware/test)

### Documentation Changes

- [x] Check, test, and update the documentation in [doc/](../doc/). Build documentation (`cd doc/manual/; make html`) to ensure no errors.

### Git Logistics

- [x] Split your contribution into logically separate changes (`git rebase --interactive`). Merge/squash/fixup commits that just fix or amend previous commits. Remove unintended changes & cleanup. See [tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase).
- [x] Write short & meaningful commit messages. Review each commit for messages (`git show`). Format:
  ```
  topic: description. < 50 characters total.
  
  Longer description. < 70 characters per line
  ```

### Licensing

See [copyright & licensing for more info](https://github.com/m-labs/artiq/blob/master/CONTRIBUTING.rst#copyright-and-sign-off).
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and are licensed under LGPLv3+.

### CODE REVIEW

**Comment by sbourdeauducq** [comment]
Could you put the unrelated style changes into a separate commit?

**Comment by lriesebos** [comment]
Separated the style changes.

**Comment by dnadlinger** [comment]
I can't really gauge interest for this either, but if we merge it upstream, some more documentation would be nice. `"""Attach a child dataset manager to this dataset manager."""` doesn't really describe what a child dataset manager is or does. Perhaps a modified version of your ClonedDatasetManager docstring would work.

**Comment by lriesebos** [comment]
I can update the documentation, but I think the fundamental question is more if this feature should merge upstream and if so, in what form.
1. There is no interest, do not upstream, we keep the hack
2. Upstream only a change like this one (with additional documentation) as an entry for other libraries (e.g. DAX)
3. Upstream the whole concept of cloning and isolating dataset managers

Let me know what your thoughts are, then I will proceed that direction.

**Comment by lriesebos** [comment]
After reconsideration I decided to drop this. The hack works fine and I do not think that I can make this change more generic. In the meanwhile I will reconsider the implementation on our side. Thanks for the feedback!

**Pull request closed without merging**
