### PR TITLE
Kasli DRTIO master: do not init rtio core until serdes PLL has locked.

### PR DESCRIPTION
**Pull request by hartytp**
fixes 1155

@jordens if you still have your test setup intact, please could you test this on your setup?

@sbourdeauducq do we need to apply similar fixes anywhere else?

### CODE REVIEW

**Comment by hartytp** [comment]
NB this will break any DRTIO masters which don't have an RTIO clock multiplier with a `pll_locked` CSR ( just Sayma master AFACIT). @sbourdeauducq do you want me to add a config option, something like `HAS_RTIO_MUL` to feature gate the new firmware?

**Comment by jordens** [comment]
Not right now. In a couple of days.

**Comment by hartytp** [comment]
@jordens thanks, there is no particular hurry for this as far as I'm concerned. Just something I was looking at while doing acceptance testing for drtio switching.

**Comment by sbourdeauducq** [comment]
I'll sort it out. Thanks for hunting down this bug.

**Comment by sbourdeauducq** [comment]
b92350b0

**Pull request closed without merging**
