### PR TITLE
Fixes for AD9910 and AD9912 drivers

### PR DESCRIPTION
**Pull request by lriesebos**
# ARTIQ Pull Request

## Description of Changes

1. Fixed typing errors in AD9910 driver and added a few return types
2. Added default pow to `set_mu()` for AD9912 (to match other `set()` function(s))

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |
|   | :sparkles: New feature |
|   | :hammer: Refactoring  |
|   | :scroll: Docs |

### All Pull Requests

- [x] Use correct spelling and grammar.
- [x] Update [RELEASE_NOTES.rst](../RELEASE_NOTES.rst) if there are noteworthy changes, especially if there are changes to existing APIs.
- [x] Close/update issues.
- [x] Check the copyright situation of your changes and sign off your patches (`git commit --signoff`, see [copyright](../CONTRIBUTING.rst#copyright-and-sign-off)).

### Code Changes

- [x] Run `flake8` to check code style (follow PEP-8 style). `flake8` has issues with parsing Migen/gateware code, ignore as necessary.
- [x] Test your changes or have someone test them. Mention what was tested and how.
- [x] Add and check docstrings and comments
- [x] Check, test, and update the [unittests in /artiq/test/](../artiq/test/) or [gateware simulations in /artiq/gateware/test](../artiq/gateware/test)

### Documentation Changes

- [x] Check, test, and update the documentation in [doc/](../doc/). Build documentation (`cd doc/manual/; make html`) to ensure no errors.

### Git Logistics

- [x] Split your contribution into logically separate changes (`git rebase --interactive`). Merge/squash/fixup commits that just fix or amend previous commits. Remove unintended changes & cleanup. See [tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase).
- [x] Write short & meaningful commit messages. Review each commit for messages (`git show`). Format:
  ```
  topic: description. < 50 characters total.
  
  Longer description. < 70 characters per line
  ```

### Licensing

See [copyright & licensing for more info](https://github.com/m-labs/artiq/blob/master/CONTRIBUTING.rst#copyright-and-sign-off).
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and are licensed under LGPLv3+.

### CODE REVIEW

**Comment by pathfinder49** [comment]
>     * Test your changes or have someone test them. Mention what was tested and how.

How have you tested this? There are subtle compiler issues in this area, which can lead to compiling code that does not produce the correct hardware outputs. See https://github.com/m-labs/artiq/issues/1463#issuecomment-643389131for an example. 

The issues I've seen were TInt64 related (https://github.com/m-labs/artiq/issues/1468). However, given those issues, it seems prudent to verify this works as expected on hardware.

**Comment by lriesebos** [comment]
No, I have not tested the RAM functions as we do not use it in our lab. Though those type annotations are obviously wrong (might have even been a typo by me).

We could stall this PR until the mentioned issues are resolved. I'll leave that to the people in charge of merging stuff.

**Comment by pmldrmota** [comment]
I am using the RAM and can confirm that a409502c7f1351a547a2e8eb33e2b96e225f0d37 fixes the `read_ram` and `write_ram` methods.

**Comment by lriesebos** [comment]
@sbourdeauducq if you think this fix is good, it can merged.

**Pull request merged**
