### PR TITLE
environment: move prepare() call's logic to HasEnvironment

### PR DESCRIPTION
**Pull request by charlesbaynham**
## Description of Changes

EnvExperiment prepare() method calls the prepare() method of all children recursively instead of just the first layer. 

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :sparkles: New feature |

### Code Changes

In the `prepare()` method of EnvExperiment, loop through the children of all children recursively calling `prepare()` on each if present.

### CODE REVIEW

**Comment by dnadlinger** [comment]
How can children opt out of this if they already implement a recursive prepare/if recursion doesn't make sense?

**Comment by sbourdeauducq** [comment]
Exactly, and you can do ``super().prepare()`` or ``EnvExperiment.prepare(self)`` explicitly if you want to call ``prepare`` on your child experiments.
This kind of breaking change also needs updating RELEASE_NOTES btw.

**Comment by charlesbaynham** [comment]
> Exactly, and you can do `super().prepare()` or `EnvExperiment.prepare(self)` explicitly if you want to call `prepare` on your child experiments.

Hmm perhaps I'm thinking of this wrong then. I've currently got a library of `HasEnvironment`s which do bits of work, some of which benefit from a `prepare` stage. I don't want them showing up in the experiment list so they can't be `EnvExperiment`s, but they still get prepared when they're children of the root `EnvExperiment`. However, `HasEnvironment` has no `prepare()` stage, so I'd have to manually `prepare` each library's children instead of calling a `super()`

Is there currently a way of having libraries of code which don't show up in the experiment list, but still get a `prepare()` stage? Or could the current "prepare all children" logic be moved into a class `PrepareChildren`, which `EnvEnvironment` then inherits from? That'd preserve current behaviour but allow for classes which inherit from both `HasEnvironment` and `PrepareChildren` but don't show up in the experiment list.

**Comment by charlesbaynham** [comment]
> 
> 
> How can children opt out of this if they already implement a recursive prepare/if recursion doesn't make sense?

You're right.

**Comment by sbourdeauducq** [comment]
> Is there currently a way of having libraries of code which don't show up in the experiment list, but still get a `prepare()` stage?

Do they also have run and analyze stages? In this case they should be Experiments, and I suggest adding an "invisible" flag that make them disappear from the list (but has no other effects, e.g. you can still schedule them using the ``artiq_client`` command-line tool).

If not, what about adding a method ``HasEnvironment.call_children_method`` that calls the corresponding method on all the children? (since the notion of "children" is introduced by ``HasEnvironment``, it makes sense that it provides some methods to interact with them)

Then ``EnvExperiment.prepare`` would simply be ``self.call_children_method("prepare")`` and you could also call use it easily in your drivers.

**Comment by charlesbaynham** [comment]
Good idea, I'll write it up

**Pull request closed without merging**
