### PR TITLE
Added clear command to artiq_flash to erase flash memory

### PR DESCRIPTION
**Pull request by marmeladapk**
# ARTIQ Pull Request

## Description of Changes

Added `clear` command to `artiq_flash` to erase flash memory

### Related Issue

Sometimes after flashing kasli or sayma for the n-th time ARTIQ won't boot. Usually clearing flash memory helps with this problem, so I added an option to do this from `artiq_flash`. Tested on Kasli v1.1.

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :sparkles: New feature |
| ✓  | :scroll: Docs |

### All Pull Requests

- [x] Use correct spelling and grammar.
- [ ] Update [RELEASE_NOTES.md](../RELEASE_NOTES.md) if there are noteworthy changes, especially if there are changes to existing APIs.
- [ ] Close/update issues.
- [x] Check the copyright situation of your changes and sign off your patches (`git commit --signoff`, see [copyright](../CONTRIBUTING.rst#copyright-and-sign-off)).

### Code Changes

- [x] Run `flake8` to check code style (follow PEP-8 style). `flake8` has issues with parsing Migen/gateware code, ignore as necessary.
- [x] Test your changes or have someone test them. Mention what was tested and how.
- [x] Add and check docstrings and comments
- [ ] Check, test, and update the conda recipes in [conda/](../doc/)
- [ ] Check, test, and update the [unittests in /artiq/test/](../artiq/test/) or [gateware simulations in /artiq/gateware/test](../artiq/gateware/test)

### Documentation Changes

- [x] Check, test, and update the documentation in [doc/](../doc/). Build documentation (`cd doc/manual/; make html`) to ensure no errors.

### Git Logistics

- [x] Split your contribution into logically separate changes (`git rebase --interactive`). Merge/squash/fixup commits that just fix or amend previous commits. Remove unintended changes & cleanup. See [tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase).
- [x] Write short & meaningful commit messages. Review each commit for messages (`git show`). Format:
  ```
  topic: description. < 50 characters total.
  
  Longer description. < 70 characters per line
  ```

### Licensing

See [copyright & licensing for more info](https://github.com/m-labs/artiq/blob/master/CONTRIBUTING.rst#copyright-and-sign-off).
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and are licensed under LGPLv3+.

### CODE REVIEW

**Comment by sbourdeauducq** [comment]
Nitpicking but I would call it "erase" since OpenOCD already calls it "erase".

**Comment by marmeladapk** [comment]
Done

**Comment by jordens** [comment]
The problem you mention would be a bug and might have other consequences (not booting is a grave one but could just as well be much more subtle problems if the flash is corrupted). I haven't seen this. Could you file an issue and next time you observe it, dump the entire flash contents in the broken state (using openocd) and do your clear-flash combo and dump it again. Then we can debug the actual issue.

**Comment by sbourdeauducq** [comment]
FWIW, I have also never seen it. Kasli has always flashed and booted reliably IME.

**Comment by marmeladapk** [comment]
> Could you file an issue and next time you observe it, dump the entire flash contents in the broken state (using openocd) and do your clear-flash combo and dump it again. Then we can debug the actual issue.

@bradbqc could you do it? You have such a problem with Sayma right now.

**Comment by sbourdeauducq** [comment]
Sometimes with some builds on Sayma, there is no output at all on the UART (@hartytp has also seen it), but I suspect this is only due to the bitstream (and likely a Vivado bug, or perhaps the legendary Ultrascale I/O timing instability across PVT and bitstream builds) and not the flash itself.

**Comment by sbourdeauducq** [comment]
https://github.com/m-labs/artiq/issues/1064

**Comment by hartytp** [comment]
What I have seen on Kasli is that sometimes it stops giving me any output on the UART. Power cycling while leaving the USB connected and also `artiq_flash -t kasli start` do not help. Removing power and USB fixes the issue.

**Pull request merged**
