### PR TITLE
Make -v/-q command line args mutually exclusive

### PR DESCRIPTION
**Pull request by drewrisinger**
Fixes m-labs#1102.
User-interface issue, where users could put both -v and -q in to leave logging level unchanged.

Signed-off-by: Drew Risinger drisinger+github@gmail.com

### CODE REVIEW

**Comment by jordens** [comment]
Could you isolate this change in one commit? (`git rebase -i`)

**Comment by sbourdeauducq** [comment]
@drewrisinger This is currently mixed with some unrelated documentation changes (see the "files changed" tab: https://github.com/m-labs/artiq/pull/1103/files)

**Comment by jordens** [comment]
ping @drewrisinger

**Comment by drewrisinger** [comment]
Closing pull request because https://github.com/m-labs/artiq/issues/1102 has been closed. Doesn't seem to have interest or worry about this issue.

**Pull request closed without merging**
