### PR TITLE
gateware: add -n/--dry-run flags for gateware target frontends

### PR DESCRIPTION
**Pull request by lriesebos**
Signed-off-by: Leon Riesebos <leon.riesebos@duke.edu>

# ARTIQ Pull Request

## Description of Changes

added a `-n` / `--dry-run` flag to the gateware target frontends. can be used for testing.

### Related Issue

None

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :sparkles: New feature |

### All Pull Requests

- [x] Use correct spelling and grammar.
- [x] Update [RELEASE_NOTES.rst](../RELEASE_NOTES.rst) if there are noteworthy changes, especially if there are changes to existing APIs.
- [ ] Close/update issues.
- [x] Check the copyright situation of your changes and sign off your patches (`git commit --signoff`, see [copyright](../CONTRIBUTING.rst#copyright-and-sign-off)).

### Code Changes

- [ ] Run `flake8` to check code style (follow PEP-8 style). `flake8` has issues with parsing Migen/gateware code, ignore as necessary.
- [ ] Test your changes or have someone test them. Mention what was tested and how.
- [ ] Add and check docstrings and comments
- [ ] Check, test, and update the [unittests in /artiq/test/](../artiq/test/) or [gateware simulations in /artiq/gateware/test](../artiq/gateware/test)

### Documentation Changes

- [ ] Check, test, and update the documentation in [doc/](../doc/). Build documentation (`cd doc/manual/; make html`) to ensure no errors.

### Git Logistics

- [ ] Split your contribution into logically separate changes (`git rebase --interactive`). Merge/squash/fixup commits that just fix or amend previous commits. Remove unintended changes & cleanup. See [tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase).
- [ ] Write short & meaningful commit messages. Review each commit for messages (`git show`). Format:
  ```
  topic: description. < 50 characters total.
  
  Longer description. < 70 characters per line
  ```

### Licensing

See [copyright & licensing for more info](https://github.com/m-labs/artiq/blob/master/CONTRIBUTING.rst#copyright-and-sign-off).
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and are licensed under LGPLv3+.

### CODE REVIEW

**Comment by sbourdeauducq** [comment]
What is the purpose/use scenario of this?

**Comment by lriesebos** [comment]
we use it for a quick test of our kasli json descriptions and kc705 gateware descriptions. each of our gateware commits triggers a pipeline in which we dry run all gateware builds to check for obvious mistakes. our hydra server then picks it up once a day to actually build the gateware.

feel free to close this PR it if you don't see fit.

**Comment by sbourdeauducq** [comment]
Does this do significantly more than check the JSON against the schema?

**Comment by lriesebos** [comment]
for kasli, it would primarily be a frontend to check against the JSON schema. for kc705 it checks if pin maps etc are at least addressed correctly.

**Comment by sbourdeauducq** [comment]
> for kc705 it checks if pin maps etc are at least addressed correctly.

Does it?
I suggest you simply use jsonschema otherwise, i.e. https://stackoverflow.com/questions/14539338/how-do-i-verify-if-a-json-data-satisfy-a-json-schema-specification

**Pull request closed without merging**
