### PR TITLE
EnumerationValue with one choice defaults to that single choice

### PR DESCRIPTION
**Pull request by lriesebos**
Signed-off-by: Leon Riesebos <leon.riesebos@duke.edu>

# ARTIQ Pull Request

## Description of Changes

`EnumerationValue` with only one choice will default to that choice if no default was provided.

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :sparkles: New feature |

### All Pull Requests

- [x] Use correct spelling and grammar.
- [x] Update [RELEASE_NOTES.rst](../RELEASE_NOTES.rst) if there are noteworthy changes, especially if there are changes to existing APIs.
- [x] Close/update issues.
- [x] Check the copyright situation of your changes and sign off your patches (`git commit --signoff`, see [copyright](../CONTRIBUTING.rst#copyright-and-sign-off)).

### Code Changes

- [x] Run `flake8` to check code style (follow PEP-8 style). `flake8` has issues with parsing Migen/gateware code, ignore as necessary.
- [x] Test your changes or have someone test them. Mention what was tested and how.
- [x] Add and check docstrings and comments
- [x] Check, test, and update the [unittests in /artiq/test/](../artiq/test/) or [gateware simulations in /artiq/gateware/test](../artiq/gateware/test)

### Documentation Changes

- [x] Check, test, and update the documentation in [doc/](../doc/). Build documentation (`cd doc/manual/; make html`) to ensure no errors.

### Git Logistics

- [x] Split your contribution into logically separate changes (`git rebase --interactive`). Merge/squash/fixup commits that just fix or amend previous commits. Remove unintended changes & cleanup. See [tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase).
- [x] Write short & meaningful commit messages. Review each commit for messages (`git show`). Format:
  ```
  topic: description. < 50 characters total.
  
  Longer description. < 70 characters per line
  ```

### Licensing

See [copyright & licensing for more info](https://github.com/m-labs/artiq/blob/master/CONTRIBUTING.rst#copyright-and-sign-off).
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and are licensed under LGPLv3+.

### CODE REVIEW

**Comment by sbourdeauducq** [comment]
I'm not sure if this is a good idea. ``NoDefault`` can currently be used to ensure that the user pays attention to the parameter and supplies a value. The patch would negate that benefit (note that enumeration values are potentially dynamically generated, so an algorithm may happen to produce only one choice in some cases depending on other factors).

**Comment by lriesebos** [comment]
Fair point. Would this be acceptable if we add a class `FirstChoice` which can be used instead of `NoDefault` to default on the first choice in the enumeration (assuming at least one is given)?

**Comment by sbourdeauducq** [comment]
Sounds unnecessarily complicated. Why not just put the singleton's value as default?

**Comment by lriesebos** [comment]
We have some situations where we have dynamically generated enumerations with an optional user-configurable default (class variable). In case no user-default was configured and the generated enumeration only has one choice, we can have that choice as default such that the user does not have to provide it when not using the dashboard.

Though I guess you are right and this situation might be too specific to actually add a feature for. Will close the PR.

**Pull request closed without merging**
