### PR TITLE
Tpz

### PR DESCRIPTION
**Pull request by pathfinder49**
Thorlabs Tcubes fixes:
- flake8
- fix TPZ constructor after move to asyncio
- Tcube fix docummentation in set_channel_enable_state

### CODE REVIEW

**Comment by hartytp** [comment]
We considered both approaches and felt that, in this particular case, putting a 'run_until_complete' in the constructor was cleaner than making the user call some other method after construction but before any voltage setting calls. Is there some issue with our approach that I'm not seeing? Otherwise I guess we set the voltage limit to 0 in the constructor, document the need to query the voltage limit after construction and add a 'run_until_complete' to the controller.

**Comment by sbourdeauducq** [comment]
Yes: ``get_event_loop()`` may create an event loop. If this happens before the user sets an alternate event loop (required e.g. on Windows with ``ProactorEventLoop`` in some cases) we are in trouble.

**Comment by pathfinder49** [comment]
Sorry, didn't mean to push that last bit. Will fix tomorrow.

**Comment by jordens** [comment]
A nit: is there no way to abbreviate the cross references and use relative ones? IIRC you can drop the module and class path if the crossref is local.

**Comment by pathfinder49** [comment]
Thanks for the feedback. Fixed and ready for review.

**Comment by sbourdeauducq** [comment]
Thanks!

**Pull request merged**
