### PR TITLE
artiq_flash: wrap paramiko commands in bash login shell

### PR DESCRIPTION
**Pull request by lriesebos**
Wrap the remote SSH commands of `artiq_flash` (using paramiko) in a bash login shell.
The login shell will load the nix environment on non-nixos systems, required to get openocd in `$PATH` when installed in the nix environment of a system.
See also https://forum.m-labs.hk/d/182-remote-artiq-flash-openocd-command-not-found

I do not have a NixOS system, so I have only tested the changes on Ubuntu 20.04.

It would be nice to have this fix also in the `release-6` branch.

Signed-off-by: Leon Riesebos <leon.riesebos@duke.edu>

# ARTIQ Pull Request

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |

### All Pull Requests

- [x] Use correct spelling and grammar.
- [x] Update [RELEASE_NOTES.rst](../RELEASE_NOTES.rst) if there are noteworthy changes, especially if there are changes to existing APIs.
- [x] Close/update issues.
- [x] Check the copyright situation of your changes and sign off your patches (`git commit --signoff`, see [copyright](../CONTRIBUTING.rst#copyright-and-sign-off)).

### Code Changes

- [x] Run `flake8` to check code style (follow PEP-8 style). `flake8` has issues with parsing Migen/gateware code, ignore as necessary.
- [x] Test your changes or have someone test them. Mention what was tested and how.
- [x] Add and check docstrings and comments
- [x] Check, test, and update the [unittests in /artiq/test/](../artiq/test/) or [gateware simulations in /artiq/gateware/test](../artiq/gateware/test)

### Documentation Changes

- [x] Check, test, and update the documentation in [doc/](../doc/). Build documentation (`cd doc/manual/; make html`) to ensure no errors.

### Git Logistics

- [x] Split your contribution into logically separate changes (`git rebase --interactive`). Merge/squash/fixup commits that just fix or amend previous commits. Remove unintended changes & cleanup. See [tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase).
- [x] Write short & meaningful commit messages. Review each commit for messages (`git show`). Format:
  ```
  topic: description. < 50 characters total.
  
  Longer description. < 70 characters per line
  ```

### Licensing

See [copyright & licensing for more info](https://github.com/m-labs/artiq/blob/master/CONTRIBUTING.rst#copyright-and-sign-off).
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and are licensed under LGPLv3+.

### CODE REVIEW

**Comment by lriesebos** [comment]
@sbourdeauducq is it reasonable to also get this fix in `release-6`?

**Comment by sbourdeauducq** [comment]
Maybe, let's use this for a while in beta and see if there are any bugs.

**Comment by lriesebos** [comment]
> Maybe, let's use this for a while in beta and see if there are any bugs.

@sbourdeauducq , do you think it is tested enough to backport to ARTIQ 6?

**Comment by sbourdeauducq** [comment]
Ok

**Pull request merged**
