### PR TITLE
Do not redirect applet stdout/stderr to log

### PR DESCRIPTION
**Pull request by lriesebos**
# ARTIQ Pull Request

## Description of Changes

when applets spawn, various QT and GTK related messages appear that badly pollute the log. this are about 9 messages for each starting/reloading applet. these messages seem to be impossible to suppress or otherwise prevent/mitigate. at the same time, applets do not report much meaningful logs, basically nothing. therefore I propose to undo #472 and have a cleaner log. any stdout/stderr messages still appear in the terminal if required for diagnosing problems with applets.

if people agree that this should be merged, I would also like to suggest a backport to ARTIQ 6. in my opinion this is basically a bug that pollutes the log.

### Related Issue

this will practically undo #472

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |

### All Pull Requests

- [x] Use correct spelling and grammar.
- [x] Update [RELEASE_NOTES.rst](../RELEASE_NOTES.rst) if there are noteworthy changes, especially if there are changes to existing APIs.
- [x] Close/update issues.
- [x] Check the copyright situation of your changes and sign off your patches (`git commit --signoff`, see [copyright](../CONTRIBUTING.rst#copyright-and-sign-off)).

### Code Changes

- [x] Run `flake8` to check code style (follow PEP-8 style). `flake8` has issues with parsing Migen/gateware code, ignore as necessary.
- [x] Test your changes or have someone test them. Mention what was tested and how.
- [x] Add and check docstrings and comments
- [x] Check, test, and update the [unittests in /artiq/test/](../artiq/test/) or [gateware simulations in /artiq/gateware/test](../artiq/gateware/test)

### Documentation Changes

- [x] Check, test, and update the documentation in [doc/](../doc/). Build documentation (`cd doc/manual/; make html`) to ensure no errors.

### Git Logistics

- [x] Split your contribution into logically separate changes (`git rebase --interactive`). Merge/squash/fixup commits that just fix or amend previous commits. Remove unintended changes & cleanup. See [tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase).
- [x] Write short & meaningful commit messages. Review each commit for messages (`git show`). Format:
  ```
  topic: description. < 50 characters total.
  
  Longer description. < 70 characters per line
  ```

### Licensing

See [copyright & licensing for more info](https://github.com/m-labs/artiq/blob/master/CONTRIBUTING.rst#copyright-and-sign-off).
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and are licensed under LGPLv3+.

### CODE REVIEW

**Comment by sbourdeauducq** [comment]
> these messages seem to be impossible to suppress or otherwise prevent/mitigate.

There are no such messages on my machines, so I doubt they are "impossible" to prevent.

What are they?

**Comment by lriesebos** [comment]
Running Ubuntu 20.04 with the the latest ARTIQ 6 packages on Nix. We see this behavior consistently on all computers running this platform. On Fedora I have seen this too.

```
INFO:applet(plot_all):print:
INFO:applet(plot_all):print:(process:30733): Gtk-WARNING **: 18:46:55.664: Locale not supported by C library.
INFO:applet(plot_all):print:	Using the fallback 'C' locale.
INFO:applet(plot_all):print:Gtk-Message: 18:46:55.688: Failed to load module "canberra-gtk-module"
INFO:applet(plot_all):print:Gtk-Message: 18:46:55.688: Failed to load module "canberra-gtk-module"
INFO:applet(plot_all):print:qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
INFO:applet(plot_all):print:No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
INFO:applet(plot_all):print:Falling back to using screens root_visual.
INFO:applet(plot_all):print:qt.qpa.xcb: internal error:  void QXcbWindow::setNetWmStateOnUnmappedWindow() called on mapped window
```

**Comment by sbourdeauducq** [comment]
Are other applications other than ARTIQ affected? Have you tried cleaning up your ``~/.config`` or even starting with a fresh user account with an empty ``~``? Have you tried running under other desktop environments (KDE, GNOME, XFCE...)

Those look like bugs in the Linux GUI stack or your setup, and not in ARTIQ.

Removing the log forwarding would make applet crashes and debugging difficult, especially on Windows where there would be no console output at all otherwise.

**Comment by sbourdeauducq** [comment]
Also try Nix and non-Nix Qt applications.

**Comment by lriesebos** [comment]
Ok the QT messages are probably related to OpenGL. By setting `export QT_XCB_GL_INTEGRATION=none` I get rid of those. As a side note, recently we realized that applet rendering performance is much worse on linux compared to windows, that might also be related to OpenGL support for Nix packages on non-NixOS systems. This was found in https://github.com/NixOS/nixpkgs/issues/66755 and https://github.com/NixOS/nixpkgs/issues/34894#issuecomment-541037136. Using [nixGL](https://github.com/guibou/nixGL) also seems to remove the QT messages, but rendering performance of applets does not improve. Hence, this solution does not seem very practical. Have OpenGL related problems appeared before?

The GTK locale message can be suppressed by using `export LC_ALL=C`.

The canberra message I can not get rid of so far.

Native applications do not seem to show these messages. Fresh ubuntu installations seem to have all messages from the start.

**Comment by sbourdeauducq** [comment]
I'm not sure if Qt uses OpenGL at all for rendering most applets. I suspect the GL dependencies are mostly software bloat.

**Comment by sbourdeauducq** [comment]
Could you work with Qt/Gtk/Nix upstream and get it fixed properly? This is not a problem in ARTIQ.

**Pull request closed without merging**
