### PR TITLE
master/scheduler: Fix priority/due date precedence order when waiting to prepare

### PR DESCRIPTION
**Pull request by dnadlinger**
@pmldrmota: This should do it.

### CODE REVIEW

**Comment by sbourdeauducq** [comment]
Should this be mentioned in the release notes and/or applied to the release-5 branch?

**Comment by dnadlinger** [comment]
I was torn, but left it off because it took several years for a situation to appear where this happens in practice, so it neither seemed to be a highlight or a breaking change. Happy to add a one-liner if you want to go for more complete release-notes.

And yes, this is strictly a bug fix and can go onto release-5.

**Comment by jordens** [comment]
Is it possible that this fixes #1433?

**Comment by dnadlinger** [comment]
This should only apply for due-date runs, and even those would have been prepared correctly once the pool status changed (e.g. when submitting a deletion).

**Pull request merged**
